// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type BSSyncronyMetadata struct {
	Uuid  string `json:"'uuid'"`
	Value []byte `json:"'value'"`
}

type Meta struct {
	Key   string         `json:"'key'"`
	Value sql.NullString `json:"'value'"`
}

type SqliteSequence struct {
	Name interface{} `json:"name"`
	Seq  interface{} `json:"seq"`
}

type TMArea struct {
	Uuid         string         `json:"'uuid'"`
	Title        sql.NullString `json:"'title'"`
	Visible      sql.NullInt64  `json:"'visible'"`
	Index        sql.NullInt64  `json:"'index'"`
	Cachedtags   []byte         `json:"'cachedtags'"`
	Experimental []byte         `json:"experimental"`
}

type TMAreaTag struct {
	Areas string `json:"'areas'"`
	Tags  string `json:"'tags'"`
}

type TMChecklistItem struct {
	Uuid                 string          `json:"'uuid'"`
	Usermodificationdate sql.NullFloat64 `json:"'usermodificationdate'"`
	Creationdate         sql.NullFloat64 `json:"'creationdate'"`
	Title                sql.NullString  `json:"'title'"`
	Status               sql.NullInt64   `json:"'status'"`
	Stopdate             sql.NullFloat64 `json:"'stopdate'"`
	Index                sql.NullInt64   `json:"'index'"`
	Task                 sql.NullString  `json:"'task'"`
	Leavestombstone      sql.NullInt64   `json:"'leavestombstone'"`
	Experimental         []byte          `json:"experimental"`
}

type TMCommand struct {
	Uuid         string          `json:"'uuid'"`
	Creationdate sql.NullFloat64 `json:"'creationdate'"`
	Type         sql.NullInt64   `json:"'type'"`
	Info         []byte          `json:"'info'"`
}

type TMContact struct {
	Uuid               string         `json:"'uuid'"`
	Displayname        sql.NullString `json:"'displayname'"`
	Firstname          sql.NullString `json:"'firstname'"`
	Lastname           sql.NullString `json:"'lastname'"`
	Emails             sql.NullString `json:"'emails'"`
	Appleaddressbookid sql.NullString `json:"'appleaddressbookid'"`
	Index              sql.NullInt64  `json:"'index'"`
}

type TMMetaItem struct {
	Uuid  string `json:"'uuid'"`
	Value []byte `json:"'value'"`
}

type TMSettings struct {
	Uuid                         string          `json:"'uuid'"`
	Loginterval                  sql.NullInt64   `json:"'loginterval'"`
	Manuallogdate                sql.NullFloat64 `json:"'manuallogdate'"`
	Grouptodaybyparent           sql.NullInt64   `json:"'grouptodaybyparent'"`
	Urischemeauthenticationtoken sql.NullString  `json:"'urischemeauthenticationtoken'"`
	Experimental                 []byte          `json:"experimental"`
}

type TMTag struct {
	Uuid         string          `json:"'uuid'"`
	Title        sql.NullString  `json:"'title'"`
	Shortcut     sql.NullString  `json:"'shortcut'"`
	Useddate     sql.NullFloat64 `json:"'useddate'"`
	Parent       sql.NullString  `json:"'parent'"`
	Index        sql.NullInt64   `json:"'index'"`
	Experimental []byte          `json:"experimental"`
}

type TMTask struct {
	Uuid                            string          `json:"uuid"`
	LeavesTombstone                 sql.NullInt64   `json:"leavesTombstone"`
	CreationDate                    sql.NullFloat64 `json:"creationDate"`
	UserModificationDate            sql.NullFloat64 `json:"userModificationDate"`
	Type                            sql.NullInt64   `json:"type"`
	Status                          sql.NullInt64   `json:"status"`
	StopDate                        sql.NullFloat64 `json:"stopDate"`
	Trashed                         sql.NullInt64   `json:"trashed"`
	Title                           sql.NullString  `json:"title"`
	Notes                           sql.NullString  `json:"notes"`
	NotesSync                       sql.NullInt64   `json:"notesSync"`
	CachedTags                      []byte          `json:"cachedTags"`
	Start                           sql.NullInt64   `json:"start"`
	StartDate                       sql.NullInt64   `json:"startDate"`
	StartBucket                     sql.NullInt64   `json:"startBucket"`
	ReminderTime                    sql.NullInt64   `json:"reminderTime"`
	LastReminderInteractionDate     sql.NullFloat64 `json:"lastReminderInteractionDate"`
	Deadline                        sql.NullInt64   `json:"deadline"`
	DeadlineSuppressionDate         sql.NullInt64   `json:"deadlineSuppressionDate"`
	T2DeadlineOffset                sql.NullInt64   `json:"t2_deadlineOffset"`
	Index                           sql.NullInt64   `json:"index"`
	TodayIndex                      sql.NullInt64   `json:"todayIndex"`
	TodayIndexReferenceDate         sql.NullInt64   `json:"todayIndexReferenceDate"`
	Area                            sql.NullString  `json:"area"`
	Project                         sql.NullString  `json:"project"`
	Heading                         sql.NullString  `json:"heading"`
	Contact                         sql.NullString  `json:"contact"`
	UntrashedLeafActionsCount       sql.NullInt64   `json:"untrashedLeafActionsCount"`
	OpenUntrashedLeafActionsCount   sql.NullInt64   `json:"openUntrashedLeafActionsCount"`
	ChecklistItemsCount             sql.NullInt64   `json:"checklistItemsCount"`
	OpenChecklistItemsCount         sql.NullInt64   `json:"openChecklistItemsCount"`
	Rt1RepeatingTemplate            sql.NullString  `json:"rt1_repeatingTemplate"`
	Rt1RecurrenceRule               []byte          `json:"rt1_recurrenceRule"`
	Rt1InstanceCreationStartDate    sql.NullInt64   `json:"rt1_instanceCreationStartDate"`
	Rt1InstanceCreationPaused       sql.NullInt64   `json:"rt1_instanceCreationPaused"`
	Rt1InstanceCreationCount        sql.NullInt64   `json:"rt1_instanceCreationCount"`
	Rt1AfterCompletionReferenceDate sql.NullInt64   `json:"rt1_afterCompletionReferenceDate"`
	Rt1NextInstanceStartDate        sql.NullInt64   `json:"rt1_nextInstanceStartDate"`
	Experimental                    []byte          `json:"experimental"`
	Repeater                        []byte          `json:"repeater"`
	RepeaterMigrationDate           sql.NullFloat64 `json:"repeaterMigrationDate"`
}

type TMTaskTag struct {
	Tasks string `json:"'tasks'"`
	Tags  string `json:"'tags'"`
}

type TMTombstone struct {
	Uuid              string          `json:"'uuid'"`
	Deletiondate      sql.NullFloat64 `json:"'deletiondate'"`
	Deletedobjectuuid sql.NullString  `json:"'deletedobjectuuid'"`
}

type ThingsTouchExtensionCommandStoreCommands struct {
	ID   int64          `json:"id"`
	Type sql.NullString `json:"type"`
	Body []byte         `json:"body"`
}

type ThingsTouchExtensionCommandStoreMeta struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}
